### PR TITLE
Add end to end testing example

### PR DESCRIPTION
**Pull request by viesti**
Small "tutorial" for starting&stopping a ring app and running CLJS tests against it.

### CODE REVIEW

**Comment by bensu** [comment]
This is great! Wouldn't it be more visible in a wiki?

**Comment by danielcompton** [comment]
Yep, wiki makes sense to me too.

**Comment by viesti** [comment]
True, my flow just wasn't there :) (and thought that this is readable from within a git clone, but that's probably way less useful :)).

Hmm, so anyone can edit the wiki too it seems, didn't realize that :)

**Comment by viesti** [comment]
I put the "tutorial" into the wiki now and added links into the index page too. Closing this PR and going to bed now :)

**Comment by bensu** [comment]
Cool thanks!!!

**Pull request closed without merging**
