### PR TITLE
Nashorn runner.

### PR DESCRIPTION
**Pull request by mikesperber**
Here's the Nashorn runner that grew out of #44. We couldn't get Rhino to work in any satisfactory way.

### CODE REVIEW

**Comment by bensu** [comment]
Hey @mikesperber,

This is great work. I see you chose to use [`jrunscript`](http://docs.oracle.com/javase/7/docs/technotes/tools/share/jrunscript.html) instead of [`jjs`](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/jjs.html). Looking at the docs `jrunscript` is marked as experimental and depending on the setup, it might also be an interface to Rhino. I tried `jjs` instead and it works. Is there any particular reason to use `jrunscript` vs `jjs`?

[Here](https://github.com/bensu/doo/commit/24dd0752b01ef36c94e939e29f5b7fff16e1f02b) are the changes to use `jjs` and I'd rather use that if there are no strong reasons to use `jrunscript`. Let me know what you think and if the proposed changes work for your setup.

**Comment by mikesperber** [comment]
`jjs` is not part of the Mac OS X Java distribution. (I didn't see any docs marking `jrunscript` experimental.)

**Comment by mikesperber** [comment]
I correct myself: `jjs` is somewhere in the bowels of the Mac OS X Java installation, but not on the standard path:

http://stackoverflow.com/questions/15306892/nashorn-in-jdk8-b80

**Comment by bensu** [comment]
The link I provided earlier, http://docs.oracle.com/javase/7/docs/technotes/tools/share/jrunscript.html marks it experimental and that it "may **not** be available in future versions". Should we point to that SO question in the docs for the Nashorn installation?

Let me know if it does work with `jjs`.

**Comment by mikesperber** [comment]
Sorry for taking sooo long trying this out: Indeed, `jjs` works. Many thanks!

**Pull request merged**
